
-- Update existing doctors with richer bios from web research
UPDATE doctors SET bio = 'Consultant Vascular and Onco-Interventional Radiologist at Medicover Hospital Hyderabad. Trained with European Diploma in Interventional Radiology (EDiR) and European Board of Interventional Radiology (EBIR, Vienna). Specializes in minimally invasive vascular and oncological procedures including uterine fibroid embolization, varicocele embolization, and TACE for liver tumors.', languages = ARRAY['English', 'Hindi', 'Telugu'] WHERE slug = 'dr-saiteja-namala';

UPDATE doctors SET bio = 'Senior Consultant Endovascular and Interventional Radiologist with 21+ years of experience. Trained in Vascular & Interventional Radiology (FVIR) at KEM Mumbai, Interventional Oncology (FIO) at Seoul National University Hospital Korea, and Aortic Interventional procedures at Siriraj Hospital Thailand. Founder of Maven Medical Center, Banjara Hills. Expert in varicose veins, varicocele, uterine fibroids, prostate artery embolization, and peripheral arterial disease.', languages = ARRAY['English', 'Hindi', 'Telugu'] WHERE slug = 'dr-balaji-patel-kola';

UPDATE doctors SET bio = 'Senior Consultant Interventional Radiologist at Manipal Hospitals Bangalore (Hebbal & Yeshwanthpur). Holds MBBS, MD Radiology, and FRCR. Experienced in both vascular and non-vascular interventions including percutaneous biopsies, abscess drainage, biliary procedures, radiofrequency ablation, uterine artery embolization, varicocele embolization, and peripheral vascular interventions.', qualification = 'MBBS, MD, FRCR', languages = ARRAY['English', 'Hindi', 'Kannada'] WHERE slug = 'dr-rajesh-helavar';

UPDATE doctors SET bio = 'Highly skilled Interventional Radiologist at Manipal Hospitals Delhi with over a decade of experience in vascular and non-vascular interventional procedures. Holds FVIR fellowship and specializes in peripheral angioplasty, uterine fibroid embolization, varicocele embolization, TACE, and deep vein thrombosis management.', languages = ARRAY['English', 'Hindi'] WHERE slug = 'dr-sahil-bansal';

UPDATE doctors SET bio = 'Experienced Vascular & Interventional Radiologist based in Vijayawada. Holds MBBS, MD, DNB, FVIR from HCG Bangalore, EBIR from European Board of Interventional Radiology, and MNAMS. Specializes in minimally invasive treatments for varicose veins, varicocele, uterine fibroids, and peripheral arterial disease.', languages = ARRAY['English', 'Hindi', 'Telugu'] WHERE slug = 'dr-vineel-inampudi';

UPDATE doctors SET bio = 'Consultant Interventional Radiologist at Pinhole IR Clinic and SIMS Hospital, Surat. Specializes in varicose vein treatments, uterine fibroid embolization, and minimally invasive vascular procedures. Known for precision care and advanced state-of-the-art interventional radiology techniques.', languages = ARRAY['English', 'Hindi', 'Gujarati'] WHERE slug = 'dr-vivek-mavani';

UPDATE doctors SET bio = 'Consultant Endovascular and Interventional Radiologist at Anu Neuro & Cardiac Sciences, Vijayawada. Specializes in image-guided minimally invasive procedures for vascular and neurological conditions. Experienced in varicose vein embolization, uterine fibroid embolization, and peripheral vascular interventions.', languages = ARRAY['English', 'Hindi', 'Telugu'] WHERE slug = 'dr-bhavani-shankar-manam';

UPDATE doctors SET bio = 'Senior Interventional Radiologist at Rela Hospital, Chennai. Specializes in diagnostic and interventional radiology procedures including biliary interventions, vascular access procedures, and image-guided biopsies.', languages = ARRAY['English', 'Hindi', 'Tamil'] WHERE slug = 'dr-deepashree';

UPDATE doctors SET bio = 'Consultant Interventional Radiologist with expertise in minimally invasive procedures. Specializes in varicose vein treatment, uterine fibroid embolization, and vascular interventions.', languages = ARRAY['English', 'Hindi', 'Telugu'] WHERE slug = 'dr-nikhil-sunkarineni';

UPDATE doctors SET bio = 'Senior Consultant Interventional Radiologist with expertise in varicose vein embolization, varicocele treatment, and other minimally invasive vascular procedures.', languages = ARRAY['English', 'Hindi', 'Marathi'] WHERE slug = 'dr-zade';

UPDATE doctors SET bio = 'Consultant Interventional Radiologist at Bharathi Hospital, Madurai. Specializes in minimally invasive procedures for varicose veins, varicocele, and uterine fibroids.', languages = ARRAY['English', 'Hindi', 'Tamil'] WHERE slug = 'dr-vinayagamani';

UPDATE doctors SET bio = 'Pioneer in Interventional Radiology with extensive experience in vascular and non-vascular procedures. Known for his expertise in minimally invasive treatments.', languages = ARRAY['English', 'Hindi', 'Kannada'] WHERE slug = 'dr-uthappa';

-- Insert the remaining 15 doctors
INSERT INTO doctors (name, slug, qualification, specialization, experience, bio, overall_success_rate, complication_rate, avg_recovery_time, languages) VALUES
('Dr. Nishant Sunkarineni', 'dr-nishant-sunkarineni', 'MBBS, MD, DM (Cardiology)', 'Interventional Cardiology', '10+ years', 'Consultant Interventional Cardiologist at Nikhil Hospital, Srinagar Colony, Hyderabad. Specializes in coronary and peripheral vascular interventions, structural heart disease management, and minimally invasive cardiac procedures.', 96, 1.5, '3-5 days', ARRAY['English', 'Hindi', 'Telugu']),
('Dr. Sibasankar Dalai', 'dr-sibasankar-dalai', 'MD, FACP, FINR (Neurology)', 'Neuro Vascular Intervention', '14+ years', 'Senior Consultant Neurovascular Interventionist at Medicover Hospital, Visakhapatnam. Fellow of American College of Physicians (FACP) and Fellow in Neurointerventional Radiology (FINR). Expert in stroke intervention, cerebral aneurysm coiling, and neuro-endovascular procedures.', 94, 2.0, '5-7 days', ARRAY['English', 'Hindi', 'Odia', 'Telugu']),
('Dr. Bhavyasree', 'dr-bhavyasree', 'MBBS, MD (Radiology)', 'Interventional Radiology', '5+ years', 'Consultant Interventional Radiologist at Gleneagles Hospital, Richmond Road, Bangalore. Trained in diagnostic and interventional radiology with expertise in uterine fibroid embolization, varicose vein treatment, and image-guided biopsies.', 95, 1.8, '2-4 days', ARRAY['English', 'Hindi', 'Kannada', 'Telugu']),
('Dr. Ankit', 'dr-ankit', 'MBBS, MD (Radiology)', 'Interventional Radiology', '5+ years', 'Consultant Interventional Radiologist at Trustwell Hospital, Bangalore. Specializes in minimally invasive vascular procedures including varicose vein treatment, varicocele embolization, and peripheral angioplasty.', 94, 2.0, '2-4 days', ARRAY['English', 'Hindi', 'Kannada']),
('Dr. Mandeep Sagar', 'dr-mandeep-sagar', 'MBBS, MD (Radiology)', 'Interventional Radiology', '8+ years', 'Consultant Interventional Radiologist at Tara Hospital, Mangalore. Experienced in varicose vein embolization, uterine fibroid embolization, and image-guided drainage procedures. Known for patient-centric approach to minimally invasive treatments.', 95, 1.5, '2-4 days', ARRAY['English', 'Hindi', 'Kannada', 'Tulu']),
('Dr. Periyalaruppan', 'dr-periyalaruppan', 'MBBS, MD (Radiology)', 'Interventional Radiology', '10+ years', 'Senior Consultant Interventional Radiologist at Anderson Diagnostics & Labs, Chennai. Over a decade of experience in image-guided interventions, vascular procedures, and minimally invasive treatments for various conditions.', 96, 1.2, '2-3 days', ARRAY['English', 'Hindi', 'Tamil']),
('Dr. Arul', 'dr-arul', 'MBBS, MD (Radiology)', 'Interventional Radiology', '8+ years', 'Consultant Interventional Radiologist at RPS Hospital, Chennai. Specializes in varicose vein treatment, uterine fibroid embolization, and peripheral vascular interventions with a focus on patient comfort and quick recovery.', 95, 1.8, '2-4 days', ARRAY['English', 'Hindi', 'Tamil']),
('Dr. Muthurajan', 'dr-muthurajan', 'MBBS, MD (Radiology)', 'Interventional Radiology', '10+ years', 'Senior Consultant Interventional Radiologist at Sri Ramakrishna Hospital, Coimbatore. Experienced in a wide range of vascular and non-vascular interventional procedures. Known for precision and excellent patient outcomes.', 96, 1.3, '2-3 days', ARRAY['English', 'Hindi', 'Tamil']),
('Dr. Raj Soni', 'dr-raj-soni', 'MBBS, MD (Radiology)', 'Interventional Radiology', '8+ years', 'Consultant Interventional Radiologist at Aartham Hospital, Ahmedabad. Specializes in varicose vein treatment, varicocele embolization, uterine fibroid embolization, and various image-guided minimally invasive procedures.', 95, 1.5, '2-4 days', ARRAY['English', 'Hindi', 'Gujarati']),
('Dr. Partha Pratim', 'dr-partha-pratim', 'MBBS, MD (Radiology)', 'Interventional Radiology', '12+ years', 'Senior Consultant Interventional Radiologist at Manipal Hospital, Kolkata. Over 12 years of experience in vascular and non-vascular interventional radiology. Expert in complex peripheral vascular interventions and tumor ablation procedures.', 96, 1.2, '3-5 days', ARRAY['English', 'Hindi', 'Bengali']),
('Dr. Praveen Keshav', 'dr-praveen-keshav', 'MBBS, MD (Radiology)', 'Interventional Radiology', '8+ years', 'Consultant Interventional Radiologist at GG Hospital, Trivandrum. Specializes in varicose vein embolization, uterine fibroid treatment, and peripheral vascular interventions with a focus on evidence-based minimally invasive care.', 95, 1.5, '2-4 days', ARRAY['English', 'Hindi', 'Malayalam']),
('Dr. Manish Kumar Yadav', 'dr-manish-kumar-yadav', 'MBBS, MD (Radiology)', 'Interventional Radiology', '8+ years', 'Consultant Interventional Radiologist at KIMS Hospital, Trivandrum. Experienced in varicose vein treatment, uterine fibroid embolization, varicocele treatment, and image-guided drainage procedures.', 95, 1.8, '2-4 days', ARRAY['English', 'Hindi', 'Malayalam']),
('Dr. Jithu Subash Babu', 'dr-jithu-subash-babu', 'MBBS, MD (Radiology)', 'Interventional Radiology', '6+ years', 'Consultant Interventional Radiologist at Baby Memorial Hospital, Calicut. Specializes in minimally invasive vascular procedures and image-guided interventions for various medical conditions.', 94, 2.0, '2-4 days', ARRAY['English', 'Hindi', 'Malayalam']),
('Dr. Thoufiq Ali', 'dr-thoufiq-ali', 'MBBS, MD (Radiology)', 'Interventional Radiology', '6+ years', 'Consultant Interventional Radiologist at KIMS Hospital, Perinthalmanna. Skilled in varicose vein treatment, varicocele embolization, and other minimally invasive vascular procedures.', 94, 2.0, '2-4 days', ARRAY['English', 'Hindi', 'Malayalam']),
('Dr. T. Seetam Kumar', 'dr-t-seetam-kumar', 'MBBS, MD (Radiology)', 'Interventional Radiology', '8+ years', 'Consultant Interventional Radiologist at Manipal Hospital, Bhubaneswar. Specializes in image-guided minimally invasive procedures including vascular interventions, tumor ablations, and drainage procedures.', 95, 1.5, '2-4 days', ARRAY['English', 'Hindi', 'Odia']);
